/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Employee {
  'id' : bigint,
  'xpPoints' : bigint,
  'name' : string,
  'badges' : Array<string>,
  'role' : string,
  'attritionRiskScore' : bigint,
  'level' : bigint,
  'department' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addContactMessage' : ActorMethod<[string, string, string], undefined>,
  'addEmployee' : ActorMethod<[string, string, string], Employee>,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getContactMessage' : ActorMethod<[string], [] | [ContactMessage]>,
  'getEmployee' : ActorMethod<[bigint], [] | [Employee]>,
  'updateEmployee' : ActorMethod<[bigint, string, string, string], Employee>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];