/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'xpPoints' : IDL.Nat,
  'name' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'role' : IDL.Text,
  'attritionRiskScore' : IDL.Nat,
  'level' : IDL.Nat,
  'department' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Employee], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getContactMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ContactMessage)],
      ['query'],
    ),
  'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
  'updateEmployee' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Employee],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'xpPoints' : IDL.Nat,
    'name' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'role' : IDL.Text,
    'attritionRiskScore' : IDL.Nat,
    'level' : IDL.Nat,
    'department' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Employee], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getContactMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContactMessage)],
        ['query'],
      ),
    'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
    'updateEmployee' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Employee],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };